### ISSUE TITLE
Entity creation aborted when battery level is 0

### ISSUE THREAD

**Issue by bartbakels** [lwestenberg/homeassistant_bold#11]
Hi;

i see an issue when adding my first bold lock. I suspect due to the fact the battery value is not yet populated. I see in the app its still calibrating the battery value.

refer to this error

Logger: homeassistant
Source: custom_components/bold/lock.py:66 
Integration: Bold 
First occurred: 17:43:27 (2 occurrences) 
Last logged: 17:48:36

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 424, in async_add_entities
    tasks = [
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 424, in <listcomp>
    tasks = [
  File "/config/custom_components/bold/lock.py", line 50, in <genexpr>
    BoldLockEntity(coordinator=coordinator, data=lock) for lock in locks
  File "/config/custom_components/bold/lock.py", line 66, in __init__
    "battery_level": data[CONF_BATTERY_LEVEL],
KeyError: 'batteryLevel'

**Comment by bartbakels** [comment]
Indeed i suspect the battery level is not available (yet) for my lock which caused the integration to abort the entity/device creation.

i replaced "battery_level": data[CONF_BATTERY_LEVEL] by

"battery_level": 0 

in the lock.py and the lock is added successfully and is controllable 

bart

**Comment by bartbakels** [comment]
Changed back after calibration and it works indeed :)

happy to test or help with new features, added some additional attributes in my own integration. But im not a coder ;)

**Comment by lwestenberg** [comment]
Closing this issue because it seems to be fixed. Feel free to reopen if it's not.
