### ISSUE TITLE
Service call failed

### ISSUE THREAD

**Issue by jurgen2005** [lwestenberg/homeassistant_bold#20]
Hi, keep getting this errors while door does open correctly.

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/bold/lock.py:108
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 01:40:07 (2 occurrences)
Last logged: 01:40:16

[547416324992] Error while unlocking: Voordeur
Traceback (most recent call last):
  File "/config/custom_components/bold/lock.py", line 102, in async_unlock
    activation_response("activationTime"),
TypeError: 'dict' object is not callable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1787, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1824, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 968, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 720, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/lock/__init__.py", line 105, in _async_unlock
    await entity.async_unlock(**service_call.data)
  File "/config/custom_components/bold/lock.py", line 108, in async_unlock
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Error while unlocking: Voordeur

**Comment by jamespreedy** [comment]
I'm getting the same issue. @lwestenberg - Please let me know if you'd like me to upload my logs too if it helps. Thanks for this integration, can stop using Homebridge now, and just stick with Home Assistant. Thank you so much!

**Comment by wejnuu** [comment]
> I'm getting the same issue. @lwestenberg - Please let me know if you'd like me to upload my logs too if it helps. Thanks for this integration, can stop using Homebridge now, and just stick with Home Assistant. Thank you so much!

Ok i managed to solve it, just make sure your Bold Connect is up and running :)

**Comment by rudizi** [comment]
Same Problem...

**Comment by wejnuu** [comment]
> Same Problem...

Do you have bold connect configured correctly? (the big button)

**Comment by rudizi** [comment]
Hi, yes the big button, clicker and iwatch works. 
Log:
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/bold/lock.py:108 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 11:42:52 (3 occurrences) 
Last logged: 13:08:21

[2560178136] Error while unlocking: Haustür
[2571503384] Error while unlocking: Haustür
[2579937144] Error while unlocking: Haustür
Traceback (most recent call last):
  File "/config/custom_components/bold/lock.py", line 92, in async_unlock
    activation_response = await self._coordinator.bold.remote_activation(
  File "/usr/local/lib/python3.10/site-packages/bold_smart_lock/bold_smart_lock.py", line 35, in remote_activation
    raise exception
  File "/usr/local/lib/python3.10/site-packages/bold_smart_lock/bold_smart_lock.py", line 31, in remote_activation
    raise ActivationError
bold_smart_lock.exceptions.ActivationError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1820, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1857, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 216, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 798, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 977, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 838, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/lock/__init__.py", line 106, in _async_unlock
    await entity.async_unlock(**remove_entity_service_fields(service_call))
  File "/config/custom_components/bold/lock.py", line 108, in async_unlock
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Error while unlocking: Haustür

**Comment by ludovandenbrink** [comment]
i have the same problem here.

unlock works one time, after this the lock status stay unlocked. 
need to reload the integration to fix the problem.
this might be a problem with bold, as it locks automatically after the specified time by design.
so the servers dont have to communicate the lock status (just my thougths). 


==============================================================================

[140077786089504] Error while unlocking: Achterdeur
Traceback (most recent call last):
  File "/config/custom_components/bold/lock.py", line 102, in async_unlock
    activation_response("activationTime"),
TypeError: 'dict' object is not callable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1849, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1889, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 226, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 798, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 980, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 838, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/lock/__init__.py", line 106, in _async_unlock
    await entity.async_unlock(**remove_entity_service_fields(service_call))
  File "/config/custom_components/bold/lock.py", line 108, in async_unlock
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Error while unlocking: Achterdeur

==============================================================================

[140077234188976] Error while unlocking: Voordeur
Traceback (most recent call last):
  File "/config/custom_components/bold/lock.py", line 102, in async_unlock
    activation_response("activationTime"),
TypeError: 'dict' object is not callable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1849, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1889, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 226, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 798, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 980, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 838, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/lock/__init__.py", line 106, in _async_unlock
    await entity.async_unlock(**remove_entity_service_fields(service_call))
  File "/config/custom_components/bold/lock.py", line 108, in async_unlock
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Error while unlocking: Voordeur

==============================================================================

2 locks, 1 Connect, 1 clicker.

**Comment by lwestenberg** [comment]
just fixed the issue, install the latest version
